config/routes.rb
Personal::Application.routes.draw do
  devise_for :users
  root 'keychains#index'

  resources :keychains do
  end


  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end

end

app/models/encryptor.rb
class Encryptor

  def self.crypt
    secret = OpenSSL::Digest::SHA256.new(Personal::Application.config.secret).digest
    crypt = ActiveSupport::MessageEncryptor.new(secret)
  end

  def self.encrypt(string)
    encrypted_data = crypt.encrypt_and_sign(string)
  end

  def self.decrypt(encrypted_data)
    crypt.decrypt_and_verify(encrypted_data)
  end

end

app/models/keychain.rb
class Keychain < ActiveRecord::Base
  
  validates_uniqueness_of :name

  def password=(string)
    self.password_encrypted = Encryptor.encrypt(string)
  end

  def password
    password_encrypted.blank? ? '' : Encryptor.decrypt(password_encrypted.to_s)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, 
         :recoverable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!
end

app/controllers/keychains_controller.rb
class KeychainsController < ApplicationController
  layout 'personal'

  def index
    flash.now[:warning] = "You are being monitored for all clicks on this app."
    @q = Keychain.search(params[:q])
    @keychains = @q.result(:distinct => true).paginate(:page => params[:page])
  end

  def new
    @keychain = Keychain.new
  end

  def create
    @keychain = Keychain.new(keychain_params)
    if @keychain.save
      redirect_to keychains_path
    else
      render :new
    end
  end

  def show
    @keychain = Keychain.find(params[:id])
    Notifications.notify_key(@keychain).deliver
    flash.now[:warning] = "The admin was notified that you viewed keychain #{@keychain.name}"
  end

  def edit
    @keychain = Keychain.find(params[:id])
  end

  def update
    @keychain = Keychain.find(params[:id])
    if @keychain.update_attributes(keychain_params)
      redirect_to keychains_path
    else
      render :edit
    end
  end

  def destroy
    @keychain = Keychain.find(params[:id])
    if @keychain.destroy
      redirect_to keychains_path
    else
      flash[:error] = @keychain.errors.full_messages.join(", ")
      redirect_to keychain_path(@keychain)
    end
  end

  private

  def keychain_params
    params.required(:keychain).permit(:name, :username, :password, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = current_user
  end

    def update_password
    @user = User.find(current_user.id)
    if @user.update_with_password(user_params)
      redirect_to root_path
    else
      render "edit"
    end
  end

  private

  def user_params
    params.required(:user).permit(:current_password, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/keychains_helper.rb
module KeychainsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/keychains/_form.html.haml
%div{:class => "row margin-base-vertical"}
  = render(:partial => 'shared/model_error_messages', :locals => {:model => @keychain})
  %div{:class => 'panel panel-default'}
    %div{:class => 'panel-heading'} 
      %strong Keychain Entry
    %div{:class => 'panel-body'}
      = form_for(@keychain, :html => {:class => 'form'}) do |f|
        %div{:class => 'form-group'}
          = f.label :name, :class => 'control-label'
          = f.text_field :name, :autofocus => true, :class => 'form-control', :placeholder => 'Keychain name'
        %div{:class => 'form-group'}
          %label Username
          = f.text_field :username, :class => 'form-control', :placeholder => 'User account'
        %div{:class => 'form-group'}
          %label Password
          = f.text_field :password, :class => 'form-control'
        %div{:class => 'form-group'}
          %label Description
          = f.text_area :description, :class => 'form-control', :rows => 5
        %div{:class => 'form-group'}
          = f.submit "Save keychain", :class => "btn btn-default"

app/views/keychains/edit.html.haml
=render('form')

app/views/keychains/index.html.haml
%table{:class => 'table table-bordered table-striped'}
  %thead
    %tr
      %th
        Name
  %tbody
    -@keychains.each do |keychain|
      %tr
        %td
          = link_to keychain.name, keychain_path(keychain)

app/views/keychains/new.html.haml
= render 'form'

app/views/keychains/show.html.haml
%div{:class => 'panel panel-default'}
  %div{:class => "panel-heading"} 
    %strong Keychain
    %span{:class => "pull-right"}
      = link_to 'Delete', keychain_path(@keychain), :method => :delete, :data => {:confirm => "Are you sure you want to delete keychain #{@keychain.name}?"}
      %span
        &nbsp;&nbsp;
      = link_to 'Edit', edit_keychain_path(@keychain)
  %div{:class => "panel-body"}
    %dl{:class => "dl-horizontal"}
      %dt
        %strong Name
      %dd= @keychain.name
    %dl{:class => "dl-horizontal"}
      %dt
        %strong Username
      %dd= @keychain.username
    %dl{:class => "dl-horizontal"}
      %dt
        %strong Password
      %dd= @keychain.password
    %dl{:class => "dl-horizontal"}
      %dt
        %strong Description
      %dd= @keychain.description

app/views/layouts/_search.html.haml
= search_form_for Keychain.search(params[:q]), :class => "navbar-form navbar-left", :role => "search" do |f|
  %div{:class => "form-group"}
    = f.text_field :name_cont, :class => 'form-control', :placeholder => 'Search'
  %button{:type => "submit", :class => "btn btn-default"}
    Submit

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Personal
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    = stylesheet_link_tag "application", :medial => "all", 'data-turbolinks-track' => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags

  %div{:class => "container"}
    %body
      %div{:class => "row margin-base-vertical"}
        %div{:class => 'col-md-6 col-md-offset-3'}
          = render(:partial => "shared/flash_messages")
          = yield

app/views/layouts/personal.html.haml
!!! 5
%html
  %head
    %title Personal
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    = stylesheet_link_tag "application", :medial => "all", 'data-turbolinks-track' => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags

    %body{:class => "#{controller.controller_name}"}
      %div{:class => "navbar navbar-default navbar-fixed-top"}
        %div{:class => "container"}
          %div{:class => "navbar-header"}
            %button{:type => "button", :class => "navbar-toggle collapsed", "data-toggle" => "collapse", "data-target" => ".navbar-collapse"}
              %span{:class => "icon-bar"}
              %span{:class => "icon-bar"}
              %span{:class => "icon-bar"}
            %a{:class => "navbar-brand", :href => "#"} Personal Web Application 
          %div{:class => "navbar-collapse collapse", :style=> "height: 1px;"}
            %ul{:class => "nav navbar-nav"}
              %li
                = link_to 'Keychains', keychains_path
              %li
                = link_to 'New Keychain', new_keychain_path
            = render 'layouts/search'
            %ul{:class => "nav navbar-nav navbar-right"}
              %li
                = link_to 'Logout', destroy_user_session_path, :method => :delete
      %div{:class => "container app_content"}
        %div{:class => 'col-md-12'}
          = render(:partial => "shared/flash_messages")
          %div{:class => "row"}
            = yield

app/views/notifications/notify_key.html.haml
%p The following key was shown to the user.
%p= @key.name
%p= "It was shown at: #{Time.now}"

app/views/shared/_flash_messages.html.haml
- if(flash[:notice])
  %div{:class => 'row'}
    %div{:class => 'alert alert-info alert-dismissable'}
      %button{:type => "button", :class => "close", "data-dismiss" => 'alert', 'aria-hidden' => "true"} &times;
      = flash[:notice]
- if(flash[:alert])
  %div{:class => 'row'}
    %div{:class => 'alert alert-danger alert-dismissable'}
      %button{:type => "button", :class => "close", "data-dismiss" => 'alert', 'aria-hidden' => "true"} &times;
      = flash[:alert]
- if(flash[:warning])
  %div{:class => 'row'}
    %div{:class => 'alert alert-warning alert-dismissable'}
      %button{:type => "button", :class => "close", "data-dismiss" => 'alert', 'aria-hidden' => "true"} &times;
      = flash[:warning]

app/views/shared/_model_error_messages.html.haml
- unless model.errors.blank?
  %div{:class => 'alert alert-danger'}
    %ul
      - model.errors.full_messages.each do |error|
        %li= error
    

app/views/users/edit.html.haml
%div{:class => "row margin-base-vertical"}
  %div{:class => 'col-md-6 col-md-offset-3'}
    = render(:partial => "shared/model_error_messages", :locals => {:model => @user})
    %div{:class => 'bordered'}
      %h4{:class => "col-lg-offset-2"} Change your password
      %p &nbsp;
      = form_for(@user, :url => {:action => 'update_password'}, :html => {:method => :patch, :class => 'form-horizontal', :role => 'form'}) do |f|
        %div{:class => 'form-group'}
          %label{:class => 'col-lg-2 control-label'} Current Password
          %div{:class => 'col-lg-8'}= f.password_field :current_password, :class => 'form-control'
        
        %div{:class => 'form-group'}
          %label{:class => 'col-lg-2 control-label'} New Password
          %div{:class => 'col-lg-8'}= f.password_field :password, :class => 'form-control'

        %div{:class => 'form-group'}
          %label{:class => 'col-lg-2 control-label'} New Password Confirmation
          %div{:class => 'col-lg-8'}= f.password_field :password_confirmation, :class => 'form-control'

        %div{:class => 'form-group'}
          %div{:class => 'col-lg-offset-2 col-lg-8'}= f.submit "Change Password", :class => "btn btn-default"